version: '3'
services:
  chat_app_nginx:
    build:
      context: ../
      dockerfile: ./docker/services/nginx/Dockerfile
    volumes:
      - "./services/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      #- "./ssl:/etc/ssl"
      - "../services/frontend:/var/www/html/static/frontend"
      - "./services/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "80:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    #command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - chat_app_users_api_php
      - chat_app_chat_api_php
      - chat_app_mysqldb

  chat_app_users_api_php:
    build:
      context: ../
      dockerfile: ./docker/services/users_api/Dockerfile
    restart: always
    env_file:
      - "./services/users_api/.env"
    volumes:
      - "./services/users_api/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "../services:/var/www/html"
    depends_on:
      - chat_app_mysqldb

  chat_app_chat_api_php:
    build:
      context: ../
      dockerfile: ./docker/services/chat_api/Dockerfile
    restart: always
    volumes:
      - "./services/chat_api/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "../services/chat_api:/var/www/html/chat_api"
    depends_on:
      - chat_app_mysqldb

  chat_app_myadmin:
    build:
      context: ../
      dockerfile: ./docker/services/myadmin/Dockerfile
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - chat_app_mysqldb

  chat_app_mysqldb:
    build:
      context: ../
      dockerfile: ./docker/services/mysql/Dockerfile
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - "./services/mysql/.env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./services/mysql/data:/var/lib/mysql"