version: '3.8'
services:
  # MySQL
  chat_app_mysqldb:
    build:
      context: ../
      dockerfile: ./docker/services/mysql/Dockerfile
    container_name: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./services/mysql/data:/var/lib/mysql"
 
 # PHP MyAdmin
  chat_app_myadmin:
    build:
      context: ../
      dockerfile: ./docker/services/myadmin/Dockerfile
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - chat_app_mysqldb
