version: '3.8'
services:
  # MySQL
  chat_app_mysqldb:
    build:
      context: ../
      dockerfile: ./docker/services/mysql/Dockerfile
    container_name: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./services/mysql/data:/var/lib/mysql"
